--------------------------------------------------------
--  파일이 생성됨 - 화요일-5월-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CODE_GROUP
--------------------------------------------------------

  CREATE TABLE "CODE_GROUP" 
   (	"GROUP_CODE_ID" VARCHAR2(20 BYTE), 
	"CODE_ID" VARCHAR2(20 BYTE), 
	"GROUP_CODE_NAME" VARCHAR2(20 BYTE), 
	"CODE_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CODE_GROUP"."GROUP_CODE_ID" IS '그룹코드ID';
   COMMENT ON COLUMN "CODE_GROUP"."CODE_ID" IS '코드ID';
   COMMENT ON COLUMN "CODE_GROUP"."GROUP_CODE_NAME" IS '그룹코드명';
   COMMENT ON COLUMN "CODE_GROUP"."CODE_NAME" IS '코드명';
--------------------------------------------------------
--  DDL for Table TB_COMMENT
--------------------------------------------------------

  CREATE TABLE "TB_COMMENT" 
   (	"COMMENT_NO" NUMBER(6,0), 
	"POST_NO" NUMBER(6,0), 
	"MEM_NO" NUMBER(6,0), 
	"COMMENT_CONTENT" VARCHAR2(1000 BYTE), 
	"COMMENT_REG_DATE" DATE DEFAULT sysdate, 
	"COMMENT_L_COUNT" NUMBER(6,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_COMMENT"."COMMENT_NO" IS '덧글번호';
   COMMENT ON COLUMN "TB_COMMENT"."POST_NO" IS '글번호';
   COMMENT ON COLUMN "TB_COMMENT"."MEM_NO" IS '작성회원번호';
   COMMENT ON COLUMN "TB_COMMENT"."COMMENT_CONTENT" IS '내용';
   COMMENT ON COLUMN "TB_COMMENT"."COMMENT_REG_DATE" IS '작성시간';
   COMMENT ON COLUMN "TB_COMMENT"."COMMENT_L_COUNT" IS '좋아요수';
   COMMENT ON TABLE "TB_COMMENT"  IS '덧글';
--------------------------------------------------------
--  DDL for Table TB_COMMENT_TAG
--------------------------------------------------------

  CREATE TABLE "TB_COMMENT_TAG" 
   (	"COMMENT_NO" NUMBER(6,0), 
	"MEM_NO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_COMMENT_TAG"."COMMENT_NO" IS '덧글번호';
   COMMENT ON COLUMN "TB_COMMENT_TAG"."MEM_NO" IS '친구회원번호';
   COMMENT ON TABLE "TB_COMMENT_TAG"  IS '덧글 태그';
--------------------------------------------------------
--  DDL for Table TB_FILE
--------------------------------------------------------

  CREATE TABLE "TB_FILE" 
   (	"FILE_NO" NUMBER(6,0), 
	"FILE_GROUP_NO" NUMBER(6,0), 
	"FILE_PATH" VARCHAR2(100 BYTE), 
	"ORI_NAME" VARCHAR2(100 BYTE), 
	"SYSTEM_NAME" VARCHAR2(100 BYTE), 
	"FILE_TYPE" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_FILE"."FILE_NO" IS '첨부파일번호';
   COMMENT ON COLUMN "TB_FILE"."FILE_GROUP_NO" IS '파일그룹번호';
   COMMENT ON COLUMN "TB_FILE"."FILE_PATH" IS '파일경로';
   COMMENT ON COLUMN "TB_FILE"."ORI_NAME" IS '원본파일명';
   COMMENT ON COLUMN "TB_FILE"."SYSTEM_NAME" IS '저장파일명';
   COMMENT ON COLUMN "TB_FILE"."FILE_TYPE" IS '파일종류';
   COMMENT ON TABLE "TB_FILE"  IS '첨부파일';
--------------------------------------------------------
--  DDL for Table TB_FILE_GROUP
--------------------------------------------------------

  CREATE TABLE "TB_FILE_GROUP" 
   (	"FILE_GROUP_NO" NUMBER(6,0), 
	"MEM_NO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_FILE_GROUP"."FILE_GROUP_NO" IS '파일그룹번호';
   COMMENT ON COLUMN "TB_FILE_GROUP"."MEM_NO" IS '회원번호';
--------------------------------------------------------
--  DDL for Table TB_FRIENDS
--------------------------------------------------------

  CREATE TABLE "TB_FRIENDS" 
   (	"MEM_NO" NUMBER(6,0), 
	"FRIENDS_NO" NUMBER(6,0), 
	"ACC_STATE" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_FRIENDS"."MEM_NO" IS '회원번호';
   COMMENT ON COLUMN "TB_FRIENDS"."FRIENDS_NO" IS '친구회원번호';
   COMMENT ON COLUMN "TB_FRIENDS"."ACC_STATE" IS '요청상태';
   COMMENT ON TABLE "TB_FRIENDS"  IS '친구';
--------------------------------------------------------
--  DDL for Table TB_GALLERY
--------------------------------------------------------

  CREATE TABLE "TB_GALLERY" 
   (	"GALLERY_NO" NUMBER(6,0), 
	"FILE_GROUP_NO" NUMBER(6,0), 
	"GALLERY_REG_DATE" DATE, 
	"GALLERY_CONTENT" VARCHAR2(400 BYTE), 
	"MEM_NO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_GALLERY"."GALLERY_NO" IS '갤러리번호';
   COMMENT ON COLUMN "TB_GALLERY"."FILE_GROUP_NO" IS '파일그룹번호';
   COMMENT ON COLUMN "TB_GALLERY"."GALLERY_REG_DATE" IS '작성시간';
   COMMENT ON COLUMN "TB_GALLERY"."GALLERY_CONTENT" IS '작성내용';
   COMMENT ON COLUMN "TB_GALLERY"."MEM_NO" IS '회원번호';
   COMMENT ON TABLE "TB_GALLERY"  IS '갤러리';
--------------------------------------------------------
--  DDL for Table TB_JOB
--------------------------------------------------------

  CREATE TABLE "TB_JOB" 
   (	"JOB_NO" NUMBER(6,0), 
	"JOB_NAME" VARCHAR2(100 BYTE), 
	"JOB_POSITION" VARCHAR2(100 BYTE), 
	"JOB_CITY" VARCHAR2(100 BYTE), 
	"JOB_INFO" VARCHAR2(200 BYTE), 
	"MEM_NO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_JOB"."JOB_NO" IS '직장번호';
   COMMENT ON COLUMN "TB_JOB"."JOB_NAME" IS '회사이름';
   COMMENT ON COLUMN "TB_JOB"."JOB_POSITION" IS '직위';
   COMMENT ON COLUMN "TB_JOB"."JOB_CITY" IS '도시';
   COMMENT ON COLUMN "TB_JOB"."JOB_INFO" IS '설명';
   COMMENT ON COLUMN "TB_JOB"."MEM_NO" IS '회원번호';
   COMMENT ON TABLE "TB_JOB"  IS '직장';
--------------------------------------------------------
--  DDL for Table TB_LIKE_COMMENT
--------------------------------------------------------

  CREATE TABLE "TB_LIKE_COMMENT" 
   (	"COMMENT_NO" NUMBER(6,0), 
	"MEM_NO" NUMBER(6,0), 
	"COMMENT_LIKE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_LIKE_COMMENT"."COMMENT_NO" IS '덧글번호';
   COMMENT ON COLUMN "TB_LIKE_COMMENT"."MEM_NO" IS '회원번호';
   COMMENT ON COLUMN "TB_LIKE_COMMENT"."COMMENT_LIKE_DATE" IS '좋아요시간';
   COMMENT ON TABLE "TB_LIKE_COMMENT"  IS '덧글 좋아요';
--------------------------------------------------------
--  DDL for Table TB_LIKE_POST
--------------------------------------------------------

  CREATE TABLE "TB_LIKE_POST" 
   (	"POST_NO" NUMBER(6,0), 
	"MEM_NO" NUMBER(6,0), 
	"POST_LIKE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_LIKE_POST"."POST_NO" IS '글번호';
   COMMENT ON COLUMN "TB_LIKE_POST"."MEM_NO" IS '회원번호';
   COMMENT ON COLUMN "TB_LIKE_POST"."POST_LIKE_DATE" IS '좋아요시간';
   COMMENT ON TABLE "TB_LIKE_POST"  IS '게시글 좋아요';
--------------------------------------------------------
--  DDL for Table TB_MEMBER
--------------------------------------------------------

  CREATE TABLE "TB_MEMBER" 
   (	"MEM_NO" NUMBER(6,0), 
	"MEM_ID" VARCHAR2(20 BYTE), 
	"MEM_PASS" VARCHAR2(20 BYTE), 
	"MEM_EMAIL" VARCHAR2(50 BYTE), 
	"MEM_NAME" VARCHAR2(20 BYTE), 
	"JOIN" CHAR(1 BYTE) DEFAULT 'y', 
	"LOGOUT_DATE" DATE DEFAULT sysdate, 
	"LOGIN" CHAR(1 BYTE) DEFAULT 'n', 
	"PROFILE_PATH" VARCHAR2(100 BYTE) DEFAULT '/bitbook/member_profile/defalutImg.jpg', 
	"COVER_PATH" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_MEMBER"."MEM_NO" IS '회원번호';
   COMMENT ON COLUMN "TB_MEMBER"."MEM_ID" IS '아이디';
   COMMENT ON COLUMN "TB_MEMBER"."MEM_PASS" IS '비밀번호';
   COMMENT ON COLUMN "TB_MEMBER"."MEM_EMAIL" IS '이메일';
   COMMENT ON COLUMN "TB_MEMBER"."MEM_NAME" IS '이름';
   COMMENT ON COLUMN "TB_MEMBER"."JOIN" IS '탈퇴유무';
   COMMENT ON COLUMN "TB_MEMBER"."LOGOUT_DATE" IS '로그아웃시간';
   COMMENT ON COLUMN "TB_MEMBER"."LOGIN" IS '로그인여부';
   COMMENT ON COLUMN "TB_MEMBER"."PROFILE_PATH" IS '프로필사진';
   COMMENT ON COLUMN "TB_MEMBER"."COVER_PATH" IS '커버사진';
   COMMENT ON TABLE "TB_MEMBER"  IS '회원';
--------------------------------------------------------
--  DDL for Table TB_MEMBER_DETAIL
--------------------------------------------------------

  CREATE TABLE "TB_MEMBER_DETAIL" 
   (	"MEM_NO" NUMBER(6,0), 
	"SKILL" VARCHAR2(50 BYTE), 
	"COLLEGE" VARCHAR2(50 BYTE), 
	"HOME" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"BIRTH" DATE, 
	"GENDER" CHAR(1 BYTE), 
	"BLOOD" VARCHAR2(50 BYTE), 
	"INTRODUCE" VARCHAR2(500 BYTE), 
	"INFO_OPEN_RANGE" CHAR(1 BYTE), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"LOGIN" CHAR(1 BYTE), 
	"LOGOUT_DATE" DATE, 
	"ADDR" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."MEM_NO" IS '회원번호';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."SKILL" IS '전문기술';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."COLLEGE" IS '대학교';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."HOME" IS '출신지';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."PHONE" IS '연락처';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."BIRTH" IS '생년월일';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."GENDER" IS '성별';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."BLOOD" IS '혈액형';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."INTRODUCE" IS '내소개';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."INFO_OPEN_RANGE" IS '공개여부';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."NICKNAME" IS '별명';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."LOGIN" IS '로그인여부';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."LOGOUT_DATE" IS '마지막로그인시간';
   COMMENT ON COLUMN "TB_MEMBER_DETAIL"."ADDR" IS '거주지
';
--------------------------------------------------------
--  DDL for Table TB_NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "TB_NOTIFICATION" 
   (	"NOT_NO" NUMBER(6,0), 
	"MEM_NO" NUMBER(6,0), 
	"NOT_TYPE" VARCHAR2(100 BYTE), 
	"NOT_DATE" DATE DEFAULT sysdate, 
	"NOT_STATE" CHAR(1 BYTE) DEFAULT 'N', 
	"REQ_MEM_NO" NUMBER(6,0), 
	"NOT_MESSAGE" VARCHAR2(100 BYTE), 
	"NOT_READ_DATE" DATE, 
	"REQ_NO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_NOTIFICATION"."NOT_NO" IS '알림번호';
   COMMENT ON COLUMN "TB_NOTIFICATION"."MEM_NO" IS '회원번호';
   COMMENT ON COLUMN "TB_NOTIFICATION"."NOT_TYPE" IS '알림종류';
   COMMENT ON COLUMN "TB_NOTIFICATION"."NOT_DATE" IS '알림시간';
   COMMENT ON COLUMN "TB_NOTIFICATION"."NOT_STATE" IS '알림상태';
   COMMENT ON COLUMN "TB_NOTIFICATION"."REQ_MEM_NO" IS '알림보낸회원';
   COMMENT ON COLUMN "TB_NOTIFICATION"."NOT_MESSAGE" IS '알림내용';
   COMMENT ON COLUMN "TB_NOTIFICATION"."NOT_READ_DATE" IS '알림확인일시';
   COMMENT ON COLUMN "TB_NOTIFICATION"."REQ_NO" IS '글번호';
   COMMENT ON TABLE "TB_NOTIFICATION"  IS '알림';
--------------------------------------------------------
--  DDL for Table TB_POST
--------------------------------------------------------

  CREATE TABLE "TB_POST" 
   (	"POST_NO" NUMBER(6,0), 
	"MEM_NO" NUMBER(6,0), 
	"POST_CONTENT" VARCHAR2(4000 BYTE), 
	"POST_REG_DATE" DATE DEFAULT sysdate, 
	"POST_OPEN_RANGE" CHAR(1 BYTE), 
	"FILE_GROUP_NO" NUMBER(6,0), 
	"POST_C_COUNT" NUMBER(6,0) DEFAULT 0, 
	"POST_L_COUNT" NUMBER(6,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_POST"."POST_NO" IS '글번호';
   COMMENT ON COLUMN "TB_POST"."MEM_NO" IS '작성회원번호';
   COMMENT ON COLUMN "TB_POST"."POST_CONTENT" IS '내용';
   COMMENT ON COLUMN "TB_POST"."POST_REG_DATE" IS '작성시간';
   COMMENT ON COLUMN "TB_POST"."POST_OPEN_RANGE" IS '공개범위';
   COMMENT ON COLUMN "TB_POST"."FILE_GROUP_NO" IS '파일그룹번호';
   COMMENT ON COLUMN "TB_POST"."POST_C_COUNT" IS '덧글수';
   COMMENT ON COLUMN "TB_POST"."POST_L_COUNT" IS '좋아요수';
   COMMENT ON TABLE "TB_POST"  IS '게시글';
--------------------------------------------------------
--  DDL for Table TB_POST_TAG
--------------------------------------------------------

  CREATE TABLE "TB_POST_TAG" 
   (	"POST_NO" NUMBER(6,0), 
	"MEM_NO" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TB_POST_TAG"."POST_NO" IS '글번호';
   COMMENT ON COLUMN "TB_POST_TAG"."MEM_NO" IS '친구회원번호';
   COMMENT ON TABLE "TB_POST_TAG"  IS '게시글 태그';
--------------------------------------------------------
--  DDL for Index CODE_GROUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CODE_GROUP_PK" ON "CODE_GROUP" ("GROUP_CODE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_COMMENT_PK" ON "TB_COMMENT" ("COMMENT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_COMMENT_TAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_COMMENT_TAG_PK" ON "TB_COMMENT_TAG" ("COMMENT_NO", "MEM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_FILE_PK" ON "TB_FILE" ("FILE_NO", "FILE_GROUP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_FILE_GROUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_FILE_GROUP_PK" ON "TB_FILE_GROUP" ("FILE_GROUP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_FRIENDS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_FRIENDS_PK" ON "TB_FRIENDS" ("MEM_NO", "FRIENDS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_GALLERY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_GALLERY_PK" ON "TB_GALLERY" ("GALLERY_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_COMPANY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_COMPANY_PK" ON "TB_JOB" ("JOB_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_LIKE_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_LIKE_COMMENT_PK" ON "TB_LIKE_COMMENT" ("COMMENT_NO", "MEM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_LIKE_POST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_LIKE_POST_PK" ON "TB_LIKE_POST" ("POST_NO", "MEM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_MEMBER_PK" ON "TB_MEMBER" ("MEM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_NOTIFICATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_NOTIFICATION_PK" ON "TB_NOTIFICATION" ("NOT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_POST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_POST_PK" ON "TB_POST" ("POST_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TB_POST_TAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_POST_TAG_PK" ON "TB_POST_TAG" ("POST_NO", "MEM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CODE_GROUP
--------------------------------------------------------

  ALTER TABLE "CODE_GROUP" ADD CONSTRAINT "CODE_GROUP_PK" PRIMARY KEY ("GROUP_CODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CODE_GROUP" MODIFY ("CODE_ID" NOT NULL ENABLE);
  ALTER TABLE "CODE_GROUP" MODIFY ("GROUP_CODE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_COMMENT
--------------------------------------------------------

  ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "TB_COMMENT_PK" PRIMARY KEY ("COMMENT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_COMMENT" MODIFY ("COMMENT_REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_COMMENT" MODIFY ("COMMENT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "TB_COMMENT" MODIFY ("MEM_NO" NOT NULL ENABLE);
  ALTER TABLE "TB_COMMENT" MODIFY ("POST_NO" NOT NULL ENABLE);
  ALTER TABLE "TB_COMMENT" MODIFY ("COMMENT_NO" NOT NULL ENABLE);
  ALTER TABLE "TB_COMMENT" MODIFY ("COMMENT_L_COUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_COMMENT_TAG
--------------------------------------------------------

  ALTER TABLE "TB_COMMENT_TAG" ADD CONSTRAINT "TB_COMMENT_TAG_PK" PRIMARY KEY ("COMMENT_NO", "MEM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_COMMENT_TAG" MODIFY ("MEM_NO" NOT NULL ENABLE);
  ALTER TABLE "TB_COMMENT_TAG" MODIFY ("COMMENT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_FILE
--------------------------------------------------------

  ALTER TABLE "TB_FILE" ADD CONSTRAINT "TB_FILE_PK" PRIMARY KEY ("FILE_NO", "FILE_GROUP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_FILE" MODIFY ("FILE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "TB_FILE" MODIFY ("SYSTEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_FILE" MODIFY ("ORI_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_FILE" MODIFY ("FILE_PATH" NOT NULL ENABLE);
  ALTER TABLE "TB_FILE" MODIFY ("FILE_GROUP_NO" NOT NULL ENABLE);
  ALTER TABLE "TB_FILE" MODIFY ("FILE_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_FILE_GROUP
--------------------------------------------------------

  ALTER TABLE "TB_FILE_GROUP" ADD CONSTRAINT "TB_FILE_GROUP_PK" PRIMARY KEY ("FILE_GROUP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_FILE_GROUP" MODIFY ("MEM_NO" NOT NULL ENABLE);
  ALTER TABLE "TB_FILE_GROUP" MODIFY ("FILE_GROUP_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_FRIENDS
--------------------------------------------------------

  ALTER TABLE "TB_FRIENDS" ADD CONSTRAINT "TB_FRIENDS_PK" PRIMARY KEY ("MEM_NO", "FRIENDS_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_FRIENDS" MODIFY ("FRIENDS_NO" NOT NULL ENABLE);
  ALTER TABLE "TB_FRIENDS" MODIFY ("MEM_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_GALLERY
--------------------------------------------------------

  ALTER TABLE "TB_GALLERY" ADD CONSTRAINT "TB_GALLERY_PK" PRIMARY KEY ("GALLERY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_GALLERY" MODIFY ("GALLERY_REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_GALLERY" MODIFY ("GALLERY_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_JOB
--------------------------------------------------------

  ALTER TABLE "TB_JOB" ADD CONSTRAINT "TB_COMPANY_PK" PRIMARY KEY ("JOB_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_JOB" MODIFY ("JOB_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_LIKE_COMMENT
--------------------------------------------------------

  ALTER TABLE "TB_LIKE_COMMENT" ADD CONSTRAINT "TB_LIKE_COMMENT_PK" PRIMARY KEY ("COMMENT_NO", "MEM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_LIKE_COMMENT" MODIFY ("COMMENT_LIKE_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_LIKE_COMMENT" MODIFY ("MEM_NO" NOT NULL ENABLE);
  ALTER TABLE "TB_LIKE_COMMENT" MODIFY ("COMMENT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_LIKE_POST
--------------------------------------------------------

  ALTER TABLE "TB_LIKE_POST" ADD CONSTRAINT "TB_LIKE_POST_PK" PRIMARY KEY ("POST_NO", "MEM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_LIKE_POST" MODIFY ("POST_LIKE_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_LIKE_POST" MODIFY ("MEM_NO" NOT NULL ENABLE);
  ALTER TABLE "TB_LIKE_POST" MODIFY ("POST_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_MEMBER
--------------------------------------------------------

  ALTER TABLE "TB_MEMBER" MODIFY ("JOIN" NOT NULL ENABLE);
  ALTER TABLE "TB_MEMBER" ADD CONSTRAINT "TB_MEMBER_PK" PRIMARY KEY ("MEM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_MEMBER" MODIFY ("MEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_MEMBER" MODIFY ("MEM_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "TB_MEMBER" MODIFY ("MEM_PASS" NOT NULL ENABLE);
  ALTER TABLE "TB_MEMBER" MODIFY ("MEM_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_MEMBER" MODIFY ("MEM_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_MEMBER_DETAIL
--------------------------------------------------------

  ALTER TABLE "TB_MEMBER_DETAIL" MODIFY ("MEM_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "TB_NOTIFICATION" ADD CONSTRAINT "TB_NOTIFICATION_PK" PRIMARY KEY ("NOT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_NOTIFICATION" MODIFY ("NOT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_POST
--------------------------------------------------------

  ALTER TABLE "TB_POST" ADD CONSTRAINT "TB_POST_PK" PRIMARY KEY ("POST_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_POST" MODIFY ("POST_L_COUNT" NOT NULL ENABLE);
  ALTER TABLE "TB_POST" MODIFY ("POST_C_COUNT" NOT NULL ENABLE);
  ALTER TABLE "TB_POST" MODIFY ("POST_OPEN_RANGE" NOT NULL ENABLE);
  ALTER TABLE "TB_POST" MODIFY ("POST_REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "TB_POST" MODIFY ("MEM_NO" NOT NULL ENABLE);
  ALTER TABLE "TB_POST" MODIFY ("POST_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_POST_TAG
--------------------------------------------------------

  ALTER TABLE "TB_POST_TAG" ADD CONSTRAINT "TB_POST_TAG_PK" PRIMARY KEY ("POST_NO", "MEM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TB_POST_TAG" MODIFY ("MEM_NO" NOT NULL ENABLE);
  ALTER TABLE "TB_POST_TAG" MODIFY ("POST_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TB_COMMENT
--------------------------------------------------------

  ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "FK_TB_COMMENT_MEM_NO_TB_MEMBER" FOREIGN KEY ("MEM_NO")
	  REFERENCES "TB_MEMBER" ("MEM_NO") ENABLE;
  ALTER TABLE "TB_COMMENT" ADD CONSTRAINT "FK_TB_COMMENT_POST_NO_TB_POST_" FOREIGN KEY ("POST_NO")
	  REFERENCES "TB_POST" ("POST_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_COMMENT_TAG
--------------------------------------------------------

  ALTER TABLE "TB_COMMENT_TAG" ADD CONSTRAINT "FK_TB_COMMENT_TAG_COMMENT_NO_T" FOREIGN KEY ("COMMENT_NO")
	  REFERENCES "TB_COMMENT" ("COMMENT_NO") ENABLE;
  ALTER TABLE "TB_COMMENT_TAG" ADD CONSTRAINT "FK_TB_COMMENT_TAG_MEM_NO_TB_ME" FOREIGN KEY ("MEM_NO")
	  REFERENCES "TB_MEMBER" ("MEM_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_FILE
--------------------------------------------------------

  ALTER TABLE "TB_FILE" ADD CONSTRAINT "FK_TB_FILE_FILE_GROUP_NO_TB_FI" FOREIGN KEY ("FILE_GROUP_NO")
	  REFERENCES "TB_FILE_GROUP" ("FILE_GROUP_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_FILE_GROUP
--------------------------------------------------------

  ALTER TABLE "TB_FILE_GROUP" ADD CONSTRAINT "FK_TB_FILE_GROUP_MEM_NO_TB_MEM" FOREIGN KEY ("MEM_NO")
	  REFERENCES "TB_MEMBER" ("MEM_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_FRIENDS
--------------------------------------------------------

  ALTER TABLE "TB_FRIENDS" ADD CONSTRAINT "FK_TB_FRIENDS_FRIENDS_NO_TB_ME" FOREIGN KEY ("FRIENDS_NO")
	  REFERENCES "TB_MEMBER" ("MEM_NO") ENABLE;
  ALTER TABLE "TB_FRIENDS" ADD CONSTRAINT "FK_TB_FRIENDS_MEM_NO_TB_MEMBER" FOREIGN KEY ("MEM_NO")
	  REFERENCES "TB_MEMBER" ("MEM_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_GALLERY
--------------------------------------------------------

  ALTER TABLE "TB_GALLERY" ADD CONSTRAINT "FK_TB_GALLERY_FILE_GROUP_NO_TB" FOREIGN KEY ("FILE_GROUP_NO")
	  REFERENCES "TB_FILE_GROUP" ("FILE_GROUP_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_LIKE_COMMENT
--------------------------------------------------------

  ALTER TABLE "TB_LIKE_COMMENT" ADD CONSTRAINT "FK_TB_LIKE_COMMENT_COMMENT_NO_" FOREIGN KEY ("COMMENT_NO")
	  REFERENCES "TB_COMMENT" ("COMMENT_NO") ENABLE;
  ALTER TABLE "TB_LIKE_COMMENT" ADD CONSTRAINT "FK_TB_LIKE_COMMENT_MEM_NO_TB_M" FOREIGN KEY ("MEM_NO")
	  REFERENCES "TB_MEMBER" ("MEM_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_LIKE_POST
--------------------------------------------------------

  ALTER TABLE "TB_LIKE_POST" ADD CONSTRAINT "FK_TB_LIKE_POST_MEM_NO_TB_MEMB" FOREIGN KEY ("MEM_NO")
	  REFERENCES "TB_MEMBER" ("MEM_NO") ENABLE;
  ALTER TABLE "TB_LIKE_POST" ADD CONSTRAINT "FK_TB_LIKE_POST_POST_NO_TB_POS" FOREIGN KEY ("POST_NO")
	  REFERENCES "TB_POST" ("POST_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "TB_NOTIFICATION" ADD CONSTRAINT "FK_TB_NOTIFICATION_MEM_NO_TB_M" FOREIGN KEY ("MEM_NO")
	  REFERENCES "TB_MEMBER" ("MEM_NO") ENABLE;
  ALTER TABLE "TB_NOTIFICATION" ADD CONSTRAINT "FK_TB_NOTIFICATION_REQ_MEM_NO_" FOREIGN KEY ("REQ_MEM_NO")
	  REFERENCES "TB_MEMBER" ("MEM_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_POST
--------------------------------------------------------

  ALTER TABLE "TB_POST" ADD CONSTRAINT "FK_TB_POST_FILE_GROUP_NO_TB_FI" FOREIGN KEY ("FILE_GROUP_NO")
	  REFERENCES "TB_FILE_GROUP" ("FILE_GROUP_NO") ENABLE;
  ALTER TABLE "TB_POST" ADD CONSTRAINT "FK_TB_POST_MEM_NO_TB_MEMBER_ME" FOREIGN KEY ("MEM_NO")
	  REFERENCES "TB_MEMBER" ("MEM_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TB_POST_TAG
--------------------------------------------------------

  ALTER TABLE "TB_POST_TAG" ADD CONSTRAINT "FK_TB_POST_TAG_MEM_NO_TB_MEMBE" FOREIGN KEY ("MEM_NO")
	  REFERENCES "TB_MEMBER" ("MEM_NO") ENABLE;
  ALTER TABLE "TB_POST_TAG" ADD CONSTRAINT "FK_TB_POST_TAG_POST_NO_TB_POST" FOREIGN KEY ("POST_NO")
	  REFERENCES "TB_POST" ("POST_NO") ENABLE;
    
create sequence s_post_no;   
create sequence s_member_no;    
create sequence s_file_no; 
create sequence s_file_group_no;
create sequence s_job_no;
create sequence s_not_no;
create sequence s_comment_no;
